---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - observer.io.observer.io
  resources:
  - observers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observer.io.observer.io
  resources:
  - observers/finalizers
  verbs:
  - update
- apiGroups:
  - observer.io.observer.io
  resources:
  - observers/status
  verbs:
  - get
  - patch
  - update
